version: '3'

services:
  dabase_rentx:
    image: postgres
    container_name: db_rentx
    restart: always
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - ignite_rentx
  app:
    build: .
    depends_on:
      - dabase_rentx
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    networks:
      - ignite_rentx

volumes:
  pgdata: {}
networks:
  ignite_rentx:
    driver: bridge
